name: Build and Deploy to Vault Repo (SSR)

on:
  push:
    tags:
      - "*-v*.*.*" # This triggers the action on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "robichaudsarah@outlook.com"
          git config --global user.name "Sarah Robichaud"

      - name: Deploy to the central showcase repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Clone the central showcase repository
          git clone https://$GH_TOKEN@github.com/sarahrobichaud/harborvault.git

          # Copy build output to the appropriate directory in the showcase repo

          touch harborvault/vite-ssr-demo/${GITHUB_REF_NAME}/.server
          mkdir -p harborvault/vite-ssr-demo/${GITHUB_REF_NAME}/build/dist/
          cp server.js harborvault/vite-ssr-demo/${GITHUB_REF_NAME}/build/server.js
          cp -R dist/* harborvault/vite-ssr-demo/${GITHUB_REF_NAME}/build/dist/

          echo "Source code available at: https://github.com/sarahrobichaud/vite-ssr-demo/tree/${GITHUB_REF_NAME}" > harborvault/vite-ssr-demo/${GITHUB_REF_NAME}/source-link.txt

          # Commit and push changes to the showcase repo
          cd harborvault
          git add .
          git commit -m "Deploy ${GITHUB_REF_NAME}"
          git push origin main
